### ISSUE TITLE
Rainmeter and Kimai in a sub-directory

### ISSUE THREAD

**Issue by Kimary94** [infeeeee/kimai-widget#1]
Hello,
I've my kimai installation on a server inside a sub-directory because on this server I'm running a site.
I've some problem with the link between kimai and kimai-cmd/rainmeter, can someone help me?

Thanks

**Comment by infeeeee** [comment]
Hello
Currently kimai-cmd builds the url from the settings.ini this way: 
`[protocol]://[serverUrl]:[serverPort]/core/json.php`
I can add a setting to change the path at the end, currently it's hardcoded.
How can you acces this json.php? Should I just add an option for folder between the port and the core folder, or do you need to change the whole path to the json.php?

**Comment by Kimary94** [comment]
I think the better choise will be:
`[protocol]://[serverUrl]:[serverPort][subfolder]/core/json.php`
Beacuse my path is www.example.com/kimai/core/json.php
In the setting should be like this:

```
protocol: http
url: www.example.com
port: 80
path: /path
```

**Comment by infeeeee** [comment]
ok, I will add this later today!

**Comment by infeeeee** [comment]
I added the subfolder option in the settings.ini. Now it's called settings.ini.example and you have to rename it to settings.ini. 

In the subfolder option you don't have to add a `/` to any end of the path, however if you add them, the program will remove them. 
Please test it, it should work: [0.0.3](https://github.com/infeeeee/kimai-widget/releases/tag/v0.0.3)

**Comment by infeeeee** [comment]
I just found out that when you click on the icon it doesn't bring you to the url of your kimai install if you use the subfolder, I will fix that later. However all other functionality should work.

**Comment by Kimary94** [comment]
Yes, if I use kimai-cmd it works but not if I use the rainmeter interface. However you have made a good work with these programs, thanks a lot

**Comment by infeeeee** [comment]
Ok, I published a new release, everything should work now, please check it [v0.0.4](https://github.com/infeeeee/kimai-widget/releases/tag/0.0.4)

**Comment by Kimary94** [comment]
It works now! 
Thanks!
